##
# (c) 2022-2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Create Release

on:
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string
      release-tag:
        required: true
        type: string
      files-globs:
        required: false
        default: |
            target/*.zip
            target/*.tgz
        type: string
      pre-release:
        required: false
        default: false
        type: boolean
      latest:
        required: false
        default: false
        type: boolean
    secrets:
      token:
        required: true

jobs:
  # Precondition the release is already tagged
  normalize:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.normalize.outputs.result }}
    steps:
      - name: Normalize version Tag
        id: normalize
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const relTag = '${{ inputs.release-tag }}'
            var release = relTag;
            if ( !relTag.startsWith('v') ) {
              release = 'v' + relTag; 
            }
            return release;

  # Changelog generation
  changelog:
    needs:
      - normalize
    runs-on: ubuntu-latest
    outputs:
      contents: ${{ steps.changelog.outputs.changes }}
    steps:
      - name: Checkout target to extract latest tag
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0

      - name: Get previous tag
        id: previous_tag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ needs.normalize.outputs.release }} | egrep -v "alpha|beta" | tail -2 | head -1)
          echo "previousTag: $name"
          echo "tag=$name" >> $GITHUB_OUTPUT

      - name: Changelog Generation
        uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ secrets.token }}
          fromTag: ${{ needs.normalize.outputs.release }}
          toTag: ${{ steps.previous_tag.outputs.tag }}
          writeToFile: true
          includeInvalidCommits: true
          excludeTypes: 'build,docs,style'

      - name: Upload artifact to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: the-changelog
          retention-days: 1
          overwrite: true
          path: CHANGELOG.md

  ## Actual creation of the release
  create:
    needs:
      - changelog
      - normalize
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: the-changelog

      - name: Check Changelog
        run: ls -l CHANGELOG.md

#      - name: Changelog Dump to File
#        run: |
#          cat > CHANGELOG.txt <<EOF
#          ${{ needs.changelog.outputs.contents }}
#          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          file: CHANGELOG.md
          name: "Release ${{ needs.normalize.outputs.release }}"
          tag_name: ${{ needs.normalize.outputs.release }}
          prerelease: ${{ inputs.pre-release }}
          files: ${{ inputs.files-globs }}
          